### ISSUE TITLE
Plugin cannot be used with Gradle 3.0M2

### ISSUE THREAD

**Issue by baron1405** [davidecavestro/gradle-jxr-plugin#2]
I have been using the gradle-jxr-plugin for quite a while with Gradle 2.*. While trying out Gradle 3.0M2 I was unable to build using the plugin due to a class not found error. The fix was simply to upgrade the plugin's build to use Gradle 2.14.1. Also upgraded the maven-jxr dependency. I have created pull request #1 with the changes.

**Comment by davidecavestro** [comment]
Just merged

**Comment by baron1405** [comment]
Can you generate a release with this change. Thanks!

**Comment by davidecavestro** [comment]
I've added to the branch gradle_3_support some of the stuff needed to publish on the gradle plugin portal. Now the plugin is available at https://plugins.gradle.org/plugin/net.davidecavestro.gradle.jxr but if I try to apply it to a simple project I get

Some problems were found with the configuration of task ':jxr'.

> No value has been specified for property 'outputDir'.
> No value has been specified for property 'footer'.
> No value has been specified for property 'windowTitle'.
> No value has been specified for property 'docTitle'.
> No value has been specified for property 'inputEncoding'.

So the release 0.2.0 probably is not currently working. 
Today I have no more spare time to address this issue, but I hope tomorrow I can check it.
Moreover the documentation should be enhanced.
I've added you as collaborator, so feel free to change what you want.

**Comment by davidecavestro** [comment]
That said I must admit I didn't understand if    the failure is due to my changes (deps on 3.0m2) or not. I should definitely take some time.

**Comment by davidecavestro** [comment]
@baron1405 just published version 0.2.1. It seems that with gradle 3 the applied plugins are not detected  in the task constructor, so I added wrapped the initialization logic into a _project.afterEvaluate_ closure.
Please check if it works for you. I also added to the README a rough hint on how to apply the plugin from the plugin portal in Gradle 3.

**Comment by baron1405** [comment]
Thanks David! I will give it a try as soon as I can and report back.

**Comment by baron1405** [comment]
Plugin loads and functions using the released Gradle 3.0.
