### ISSUE TITLE
Plugin adandoned

### ISSUE THREAD

**Issue by baron1405** [davidecavestro/gradle-jxr-plugin#3]
It appears that this plugin has been abandoned by its author. There have been no commits in three years, the version of Gradle used to build the plugin is very old, the plugin is incompatible with the upcoming Gradle 3.0 release, a pull request to address the incompatibility has not been considered by the author, and attempts to contact the author have failed.

**Comment by davidecavestro** [comment]
Sorry, I missed your request. I've just merged the pull request. Please let me know if you are interested in helping to maintain this plugin.

**Comment by baron1405** [comment]
No problem and thanks so much for merging in the pull. Certainly go ahead and close this issue since it is now happily incorrect :-)

As far as helping, I would be happy to ensure that the plugin stays current with respect to building. Not sure how much help I can be adding features.
